# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a08059b62bc7e86ab8b77923cf5a9253c57a0bb60e8e134807cccff81aea6b3a7ede69bac76ce4d90e0f22d30b57bbf7ce25b5a87450fa5bf519623b5a26471

test:
  secret_key_base: 22fa1e004250a698a4b960fb1a17036a813b2c02205ff790069dee95b8b8dd853629eeede5c4be1474f4e90348a33b3df93103af407dd57591d5d685894078c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
