source 'https://rubygems.org'

gem 'devise'

gem 'rails', '4.2.5.1'

gem 'rails-api'

gem 'spring', :group => :development

gem 'pg'

gem 'web-console', :group => :development

gem 'stripe'

gem 'rack-cors', :require => 'rack/cors'

gem 'responders', '~> 2.0'

gem 'paperclip'

gem 'aws-sdk', '< 2.0'

gem 'jbuilder'

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'shoulda'
  gem 'database_cleaner'
  gem 'selenium-webdriver'
end